---

- name: Ensure it's VMWare
  command: "dmidecode --string system-product-name > /tmp/os_version.conf"
  lineinfile:
    name: /tmp/os_version
    line: "VMware Virtual Platform"
    state: present
  check_mode: yes
  register: conf
  failed_when: (conf is failed)

- name: Update Grub.conf
  lineinfile: >
    dest={{ grub_config_path }}
    regexp="{{ item.regexp }}"
    line="{{ item.line}}"
    state=present
  with_items:
    - { regexp: "?<=GRUB_CMDLINE_LINUX_DEFAULT",
    line: GRUB_CMDLINE_LINUX_DEFAULT="nomodeset consoleblank=0 systemd.show_status=true elevator=noop"}