---
# PostgreSQL 12 form testing
- name: python3-psycopg2
  apt:
      name: python3-psycopg2
      state: present

- name: Install postgress
  apt:
      name: ['postgresql-server-dev-12', 'postgresql-12']
      state: present
      update_cache: yes
 
- name: Create db 'el'
  postgresql_db:
      name: "{{ psql_db_name }}"
      encoding: utf-8
  become: true
  become_user: postgres

- name: Create db user 'el'
  postgresql_user:
      db: "{{ psql_db_name }}"
      name: "{{ psql_db_user }}"
      password: "{{ psql_db_passwd }}"
  become: true
  become_user: postgres